build:
	 tinygo build -x -tags=dev -target=bluepill -size full -o test.elf
flash:
	 tinygo flash -x -tags=dev -target=bluepill -programmer=bmp
debug:
	 tinygo gdb -x -tags=dev -target=bluepill -programmer=bmp
